[package]
name = "pstexplorer"
version = "0.1.0"
edition = "2024"

[dependencies]
outlook-pst = "1.1"
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
ratatui = "0.30"
crossterm = "0.29"
